backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/auth/auth.controller.spec.ts, backend/src/auth/auth.controller.ts, backend/src/auth/auth.guard.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/auth.strategy.ts, backend/src/team/entity/team-member.entity.ts, backend/src/team/entity/team.entity.ts, backend/src/team/team.controller.spec.ts, backend/src/team/team.controller.ts, backend/src/team/team.module.ts, backend/src/team/team.service.spec.ts, backend/src/team/team.service.ts, backend/src/user/entity/user.entity.ts, backend/src/user/user.controller.spec.ts, backend/src/user/user.controller.ts, backend/src/user/user.module.ts, backend/src/user/user.service.spec.ts, backend/src/user/user.service.ts, backend/src/workspace/entity/workspace-member.entity.ts, backend/src/workspace/entity/workspace.entity.ts, backend/src/workspace/workspace.controller.spec.ts, backend/src/workspace/workspace.controller.ts, backend/src/workspace/workspace.module.ts, backend/src/workspace/workspace.service.spec.ts, backend/src/workspace/workspace.service.ts
- Team Entity 구성
- User Entity 구성
- Workspace Entity 구성
- Team - User 관계 Entity 구성
- User - Workspace 관계 Entity 구성
=> [feat] 기초 Entity 구성 완료 closes #4

frontend/src/data/workspace-order.ts, frontend/src/pages/main/order-dropdown/index.style.tsx, frontend/src/pages/main/workspace-card/index.tsx, frontend/src/pages/main/workspace-card/index.type.ts, frontend/src/pages/main/workspace-list/index.tsx, frontend/src/pages/main/workspace-list/index.type.ts, frontend/src/types/main-workspace.d.ts, frontend/src/utils/index.ts
- #15 
- recent 페이지에서 workspace 목록을 불러온다
- workspaces 페이지에서 workspace 목록을 불러온다
- 정렬 dropdown을 선택하는 경우 화면에는 한 박자 늦게 반영되는 문제가 있습니다. 아직 해결하지 못했는데 혹시나 `workspaceCardType` 변경된 부분 사용이 필요하실까봐 일단 PR 날립니다!
=> [feat] All Workspace API 연동 closes #15

frontend/src/components/user-profile/index.tsx, frontend/src/hooks/useAuth.ts
- closes #51 
- 로그인 api 연동
- 로그아웃 api 연동
- 인증 api 연동
=> [feat] 로그인, 로그아웃, 인증 api 연동 FE closes #51

backend/package-lock.json, backend/package.json, backend/src/auth/guard/session.guard.ts
- #5 
로그인 유저 차단 목적 Guard가 로그인 사용자의 요청을 받은 경우 루트로 리다이렉션하도록 수정함.
=> [fix] login api 동작 방식 변경 closes #51

frontend/package.json, frontend/src/api/user.ts, frontend/src/api/user.types.ts, frontend/src/components/user-profile/index.tsx, frontend/src/pages/main/workspace-list/index.tsx
- close #56 
user 관련 api 명세를 참고해서 api 호출하는걸 wrapping했습니다.
=> [feat] API 패칭 분리 close #56

frontend/src/api/user.ts, frontend/src/api/workspace.ts, frontend/src/api/workspace.type.ts, frontend/src/pages/main/workspace-list/index.tsx, frontend/src/pages/main/workspace-template/index.tsx
- #58 
- workspace 생성 api 패칭 작업
=> [feat] workspace 생성 api 패칭 closes #58

backend/src/user/user.service.ts, backend/src/workspace/dto/workspaceCreateRequest.dto.ts, backend/src/workspace/entity/workspace.entity.ts, backend/src/workspace/workspace.service.ts
- #60 
- 더이상 workspace 생성 시 name을 강제하지 않으며, 생략 시 `untitled`를 사용함.
- workspace에 thumbnail 컬럼을 추가함. (API 문서 참고)
=> [fix] workspace API 요구사항 반영 closes #60

backend/src/app.gateway.ts, backend/src/main.ts, backend/src/util/session.util.ts
- #66 
- Socket Server에 Express 세션을 꽂아 세션 정보를 접근할 수 있도록 하였음.
=> [feat] Socket 서버와 Express-Session 연결 #66

frontend/package-lock.json, frontend/package.json, frontend/src/pages/workspace/whiteboard-canvas/index.tsx, frontend/src/pages/workspace/whiteboard-canvas/index.types.tsx, frontend/src/pages/workspace/whiteboard-canvas/socket.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/types/socket.types.ts
- closes #82 
- useCanvas 리팩토링
- socket types 정의
- useSocket 구현
=> [feat] 소켓 연결 설정 closes #82

backend/src/app.gateway.ts, backend/src/object.dto.ts, backend/src/user-map.vo.ts
=> [fix] Socket API 요청 주소 변경 #66

backend/src/app.gateway.ts
- userMap.delete() 메서드 호출 위치 변경
=> [fix] Socket Disconnect 로직 수정 #66

backend/src/app.gateway.ts, backend/src/object.dto.ts
=> [feat]  Socket 이벤트 구현 closes #66

backend/src/app.gateway.ts
=> [fix] API 요청 시 workspaceId 고정 ID 제거 #66

backend/src/app.gateway.ts, backend/src/types/auth.d.ts, backend/src/types/session.d.ts
- #72 
- 연결 과정에서 유저 정보를 가져오는 과정을 연결해두었던 세션으로 가져오도록 변경함.
=> [hotfix] 소켓 서버 긴급 수정 #72

backend/src/app.gateway.ts, backend/src/util/socket/user.dao.ts
- Guest userId, nickname 변경
- enter_user 이벤트 시 color 값 전달
=> [refactor] Guest userId, nickname 변경 및 enter_user 이벤트 시 color 값 전달 #66

frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts, frontend/src/utils/fabric.utils.ts
- #76 
- 마우스 휠 이벤트에 화면이동 기능 추가
- Zoom 기능은 Ctrl + Wheel로 가능하도록 변경
- 제가 default 시점을 기준으로 그리드를 대칭으로 그렸기 때문에 중심은 아마 맞을거라고 생각합니다
- 화면을 제한하거나 하는 방법은 여러가지 따져야 할게 많아서 추후에 추가해보도록 하겠습니다.
- Zoom Out을 최대로 했을때 화면이 너무 작지 않나? 라는 생각이 들긴 하네요. 이것도 불편하면 값만 수정하면 됩니다!
=> [feat] 화이트보드 Canvas 휠 기반 화면이동 구현 closes #76

frontend/src/context/workspace.ts, frontend/src/pages/workspace/whiteboard-canvas/index.tsx, frontend/src/pages/workspace/whiteboard-canvas/socket.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasEvent.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/types/workspace-member.d.ts, frontend/src/types/workspace.d.ts, frontend/src/utils/fabric.utils.ts
- closes #87 
마우스 포인터 실시간 공유 구현
- canvas event 등록하는 useEffect를 useCanvasEvent로 분리 했는데 적절한 이름인지? 고민됩니다
- 방 입장이 안되어서 자시 자신 포인터 정보 가져와지는거 확인헀고 이거말곤 확인할 방법이 없어서 안막았는데 추후에는 자기가 보낸 소켓 이벤트는 필터링 할 예정입니다.
=> [feat] 마우스 포인터 실시간 공유 구현

backend/src/auth/auth.controller.ts, backend/src/auth/filter/unauth-redirect.filter.ts, backend/src/socket/db-access.service.ts, backend/src/socket/socket.gateway.ts, backend/src/team/team.service.ts
- #72
- 소켓 연결 초기화 시 존재하는 Workspace인지 확인함.
- 소켓 연결 초기화 중 오류 발생 시 exception 이벤트 발생
- 소켓 연결 초기화 시 최초 접근 로그인 유저에게 초기권한 부여 및 DB 기록 로직 추가
=> [feat] 유저 권한 조회 시 Workspace 확인 및 로그인 유저 최초 접근 시 DB에 기록 #72

frontend/src/App.tsx, frontend/src/pages/main/workspace-card/index.tsx, frontend/src/pages/main/workspace-template/index.tsx
- #116 
- workspace url 설정
- workspace card 클릭했을 때도 라우팅되도록 설정해두었습니다
=> [feat] workspace url 설정 closes #116

frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts, frontend/src/utils/fabric.utils.ts, frontend/src/utils/object-from-server.ts
- #77 
- cursor가 선택되는 문제 해결
- cursor를 항상 위로 올림
- Delete Action 추가
- selection 상태에서만 이벤트가 존재하도록 구현
=> [feat] Object Delete Action 추가 closes #77

backend/src/migrations/1669621214094-change-object-columns.ts, backend/src/object-database/dto/create-object.dto.ts, backend/src/object-database/dto/update-object.dto.ts, backend/src/object-database/entity/workspace-object.entity.ts, backend/src/socket/db-access.service.ts, backend/src/socket/socket.gateway.ts, backend/src/util/socket/object.dto.ts
- #132 
- Object Entity의 각 프로퍼티의 명칭 변경 (xPos, yPos -> left, top / fontsize 추가)
- Entity 수정에 따른 Migration 파일 작성
- Entity 수정에 따른 DTO 수정
- DTO 수정에 따른 Validation 로직 수정
=> [fix] Object Entity 구조 변경 closes #132

backend/src/migrations/1669639570300-change-role-type.ts, backend/src/team/entity/team-member.entity.ts, backend/src/workspace/entity/workspace-member.entity.ts
- TINYINT length 옵션 제거
- 마이그레이션 파일 수정
=> [feat] 작업내용 closes #140

backend/src/socket/db-access.service.ts
- #121
- return 시 문법 오류에 따른 잘못된 리턴값 수정
=> [hotfix] Role 탐색 및 추가 로직 리턴 타입 수정

frontend/public/manifest.json, frontend/src/components/logo/index.tsx, frontend/src/pages/workspace/header/index.tsx, frontend/src/pages/workspace/header/index.type.ts, frontend/src/pages/workspace/index.tsx, frontend/src/pages/workspace/layout/index.style.tsx, frontend/src/pages/workspace/layout/index.tsx, frontend/src/pages/workspace/toolkit/index.tsx
- #146 
- 컴포넌트 구조 조금 더 관심사에 맞게 수정해서 다시 Layout으로 묶어뒀습니다
- memo 및 useCallback 사용
- manifest 크기 오류 수정
=> [refactor] 워크스페이스 컴포넌트 레이아웃 리팩토링 closes #146

backend/src/socket/dto/user.dao.ts
- #121
- UserDAO 객체의 생성자에서 role 초기화가 누락된 부분을 추가함.
=> [hotfix] UserDAO 생성자의 role이 누락된 부분 수정 #121

frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts, frontend/src/utils/fabric.utils.ts, frontend/src/utils/object.utils.ts
- #126 
- PostIt 기본 레이아웃 설정
- Rect, TextBox, Text를 Grouping
- Height가 넘치면 fontSize를 줄이도록 설정
- 가끔 Resize 하다보면 확 작아질 때가 있는데, Resize(Scaling)에 쓰로틀링을 설정하면 해결되지 않을 까라고 생각중입니다.
=> [feat] addPostIt 구현 closes #126

frontend/patches/@types+fabric+4.5.12.patch, frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts, frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/fabric.utils.ts, frontend/src/utils/object-from-server.ts, frontend/src/utils/object.utils.ts, frontend/src/utils/socket.utils.ts
- closes #111 
- 소켓에서 받은 데이터로 객체 구현
- 자신이 보낸 메시지 필터 구현
- section은 pr되면 추가하겠습니다
- 일단 추가가 되어야 수정 삭제도 테스트할 수 있어서 10시전까지 approve 부탁드려용
=> [feat] create object 구현

backend/src/socket/data-management.service.ts, backend/src/socket/socket.gateway.ts
- disconnect 시 userMap에 저장되지 않은 회원일 경우 오류 발생
- select_object 이벤트 수정
- unselect_object 이벤트 수정
=> [feat] 객체 다중선택 구현 closes #151

frontend/patches/@types+fabric+4.5.12.patch, frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts, frontend/src/pages/workspace/whiteboard-canvas/types/workspace-member.types.ts, frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/object-from-server.ts, frontend/src/utils/object.utils.ts, frontend/src/utils/socket.utils.ts
- closes #131 #88 #86 
- 실시간 공유 init 구현
- object update 구현
- text edit 구현
- remove 구현(이슈 있음)
- select/unselect 구현
- cursor 수정
- resize는 scale 방식이라서 서버 데이터 구조를 변경해야해서 아직 안됩니다
- remove가 서버 데이터 이슈와 ungroup화 이슈로 문제가 있어 닫아놨습니다(merge전 수정 예정)
- 프로토타입 수요일전까지 만들어야할 것 같아서 한 브랜치에 다 몰아 넣은 점 죄송합니다ㅠㅠ
- 역시 급하게 하느라 리팩토링 신경을 못썻는데 오늘 날잡고 버그수정 + 리팩토링 하겠습니다.
=> [feat] object update & text edit & remove & select & cursor 실시간 공유 구현

frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/socket.utils.ts
=> [fix] socket 부분 병합 후 에러 수정

frontend/patches/@types+fabric+4.5.12.patch
- #127 
- patch file index에서 충돌이 났었어서 새로 다운 받아봄
=> [hotfix] patch 파일 새로 받음 #127

frontend/src/components/error-modal/index.style.ts, frontend/src/components/error-modal/index.tsx, frontend/src/components/error-modal/index.types.ts, frontend/src/components/github-login-button/index.tsx, frontend/src/components/modal/index.style.tsx, frontend/src/components/modal/index.tsx, frontend/src/components/modal/index.types.ts, frontend/src/components/user-profile/index.tsx, frontend/src/pages/main/delete-modal/index.style.tsx, frontend/src/pages/main/delete-modal/index.tsx, frontend/src/pages/main/rename-modal/index.style.tsx, frontend/src/pages/main/rename-modal/index.tsx, frontend/src/pages/main/workspace-menu/index.tsx, frontend/src/pages/workspace/index.style.tsx, frontend/src/pages/workspace/index.tsx, frontend/src/pages/workspace/layout/index.style.tsx, frontend/src/pages/workspace/layout/index.tsx, frontend/src/pages/workspace/share-modal/index.style.tsx, frontend/src/pages/workspace/share-modal/index.tsx, frontend/src/pages/workspace/share-modal/index.type.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
- #157 
- 모달 컴포넌트 사용하다보니까 스타일 재사용되는 부분이 많아서 일부 구조 수정했습니다
=> [refactor] 모달 컴포넌트 리팩토링 closes #157

.github/workflows/check-build.yml
=> [feat] build 체크 테스트

backend/src/socket/data-management.service.ts, backend/src/socket/dto/object-map.vo.ts, backend/src/socket/dto/object-move.dto.ts, backend/src/socket/dto/object-scale.dto.ts, backend/src/socket/socket.gateway.ts
BE - move_object, scale_object 소켓 이벤트 추가
- `move_object` 소켓 이벤트 추가
- `scale_object` 소켓 이벤트 추가
- `update_object` 이벤트 시 objectDataMap 동기화
=> [fix] move_object, scale_object 이벤트 구현 closes #168

frontend/src/utils/fabric.utils.ts, frontend/src/utils/object.utils.ts
- #127 
- selection이 해제 될 때 키다운 이벤트가 해제 돼서 발생함
- original text가 선택되지 않도록 이벤트랑 select를 막아봤음
=> [fix] delete 관련 버그 closes #127

backend/src/object-database/object-handler.service.ts, backend/src/socket/data-management.service.ts, backend/src/socket/socket.gateway.ts
=> [hotfix] init 이벤트 시 ObjectId 미반환 문제 해결 #168

frontend/src/utils/fabric.utils.ts
=> [chore] Grid line을 background로 설정 closes #172

frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/fabric.utils.ts
- object 삭제 시에 중복삭제가 일어나는 문제가 있어서 수정했습니다
=> [fix] object 중복삭제 수정

frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts, frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/socket.utils.ts
- closes #160 
- object move 변화량 방식으로 refactor
- object group move 구현
=> [feat] object group 이동구현

frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/fabric.utils.ts, frontend/src/utils/object.utils.ts
- #126 
- textBox에 마우스 이벤트 안먹히는 것 해결
- 서버에서 받아온 오브젝트에 작성자 ID를 nickname으로 변경
=> [Hotfix] Postit 관련 오류 수정

frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/fabric.utils.ts, frontend/src/utils/object-from-server.ts, frontend/src/utils/object.utils.ts, frontend/src/utils/socket.utils.ts
- closes #161 
- 단일 object scaling 구현
- 그룹 object scaling 구현
- object 업데이트 로직 변경
- 프로토타입 끝!
=> [feat] object scaling 구현

backend/src/socket/socket.gateway.ts
- #185 
- 로거 error 출력 시에 메세지 + 콜스택을 출력하도록 수정
=> [fix] 로거 출력 시 콜스택과 메세지를 모두 출력하도록 변경 closes #185

frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
=> [hotfix] PostIt 작성자 표시 롤백 closes #126

backend/src/socket/dto/object-move.dto.ts, backend/src/socket/socket.gateway.ts
BE - Socket 서버 move_object 이벤트 rollback
- move_object 이벤트의 반환 객체에서 delft -> left, dtop -> top으로 변경
=> [feat] Socket 서버 move_object 이벤트 rollback closes #210

backend/src/workspace/workspace.service.ts
- workspaceId가 올바르지 않을 경우 예외 처리
- file의 경로가 올바르지 않을 경우 예외 처리
=> [hotfix] thumbnail 업데이트 관련 예외처리 추가 #198

frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/utils/fabric.utils.ts, frontend/src/utils/object-from-server.ts, frontend/src/utils/object-to-server.ts
- closes #202 
- draw 객체 선택 허용
- draw 객체 초기화 로직 수정
- draw 객체 CRUD 실시간 공유
- cursor 객체 속성 수정
=> [feat] socket draw 실시간 공유 구현

backend/src/object-database/schema/template-bucket.schema.ts, backend/src/workspace/workspace.controller.ts, backend/src/workspace/workspace.module.ts, backend/src/workspace/workspace.service.ts
- #219 
- Workspace Service에 Workspace 복제 메서드 / Template 조회 기능 추가
=> [feat] 템플릿 목록 조회 및 캔버스 복제 기능 추가

backend/src/socket/pipe/object-transform.pipe.ts
- #192 
- 유효성 검증 로직에서 체크 대상 property들 중 제공되지 않은 것들은 검증을 생략한다.
=> [hotfix] Update 유효성 검증 로직 오류 수정 fix #192

frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/object-from-server.ts
- #126 
- 특정 워크스페이스 참여자 목록을 받아와서 거기서 nickname을 탐색해서 찾아냄
- 게스트는 참여자가 아니면 이름이 뜨지 않습니다.
=> [fix] postit에 usernickname 표시 #126

frontend/package-lock.json, frontend/package.json, frontend/src/utils/object-from-server.ts, frontend/src/utils/object-to-server.ts
- #235 
- lz-string 이라는 라이브러리를 사용해서 간단하게 압축함
- 압축 결과물은 string 이라서 서버에서 처리할 것은 없음
- 이전 버전 Original Path로 오는 것들은 앞에 "M"으로 시작하기 때문에 처리해줬음
- scaling시 서버에서 받아온 Object가 TextBox가 같이 커지는 현상 수정
- length가 5000-> 1000으로 줄어드는 것 확인
- 절반 이상 줄어드는 것 같습니다.
=> [feat] Path string 압축 closes #235

backend/src/socket/db-access.service.ts, backend/src/types/workspace.d.ts, backend/src/user/dto/partial-search.dto.ts, backend/src/user/pipe/part-search-transform.pipe.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts
- #239 
- 페이지네이션을 위해 필터에 따른 워크스페이스 목록 부분 조회 기능 추가
- 소켓 연결/종료 시 Update 시간을 변경하도록 수정함. (수정 시마다 뜨도록 하고자 한다면, 나중에 스로틀이라도 걸 예정. 지금은 편법으로 로그인/로그아웃 시에만 갱신하도록 구성.)
=> [feat] 워크스페이스 부분 조회 기능 추가 #239

frontend/src/api/user.types.ts, frontend/src/api/workspace.ts, frontend/src/api/workspace.type.ts, frontend/src/pages/main/workspace-card/index.style.tsx, frontend/src/pages/main/workspace-card/index.tsx, frontend/src/pages/main/workspace-list/index.tsx, frontend/src/pages/main/workspace-list/index.type.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts, frontend/src/utils/fabric.utils.ts
- closes #230 
- 기능적으로 구현하긴 했는데 최적화를 고려를 안해서 너무 많이 api 요청이 일어납니다.. 일단 다른게 우선이라 나중에 이건 또 최적화하겠습니다.
=> [feat] 썸네일 기능 구현

frontend/src/pages/workspace/whiteboard-canvas/index.style.tsx, frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts, frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts, frontend/src/utils/fabric.utils.ts, frontend/src/utils/object-from-server.ts, frontend/src/utils/object.utils.ts
- #234 
- canvas resize 이벤트
- 포스트잇/섹션 색상 구분
- flip/rotation 방지
- 텍스트 편집 및 이동 동시 편집
- 포스트잇 텍스트 박스 동기화
- 트랙패드로 뒤로가기되는 문제도 css overscroll-behavior 속성으로 해결해보려고 했는데 안 먹히더라구요,,
=> [feat] 화이트보드 UX 개선

frontend/src/pages/main/workspace-list/index.tsx, frontend/src/pages/workspace/export-modal/index.tsx, frontend/src/utils/fabric.utils.ts
- closes #247 
- socket 거치는 object만 export 되도록 걸어놨습니다.
- 찍히는건 여전히 찍힐텐데.. 이거 고치려면 canvas가상으로 하나 만들고 그린담에 image만들어야해서 오버헤드가 너무 많이 드는것 같아서 일단 나중에 고려해보겠습니다
=> [hotfix] export시 mouse cursor도 포함하는 문제 해결

backend/src/socket/socket.gateway.ts
BE - 배포를 위한 Log 추가
- 각 이벤트에 `workspace명 / 이벤트명 / 유저ID` 내용의 로그 추가
=> [feat] Event 분석을 위한 Log 추가 closes #258

frontend/src/api/user.ts, frontend/src/data/workspace-order.ts, frontend/src/index.tsx, frontend/src/pages/main/workspace-list/index.tsx, frontend/src/pages/workspace/member-role/index.tsx, frontend/src/pages/workspace/zoom-controller/index.style.tsx, frontend/src/utils/convert-time.utils.ts
- closes #269 #267
- 권한 select modal 클릭 반응 수정
- zoom-in-out 클릭 반응 수정
- 워크스페이스 목록 무한 스크롤
=> [feat] UX 개선 및 무한 스크롤 추가

backend/package-lock.json, backend/src/socket/socket.gateway.ts
- #274 
- 웹소켓 서버 HTTP Long polling 비활성화
=> [fix] 웹소켓 서버 long polling 비활성화 closes #274

backend/package-lock.json, backend/src/socket/socket.gateway.ts
=> Revert "[fix] 웹소켓 서버 long polling 비활성화 closes #274"

backend/src/socket/object-management.service.ts
- #277 
- ObjectManagemkentService에서 캐싱 제거
=> [fix] 백엔드 Object 캐시 제거

backend/src/socket/object-management.service.ts
- #277
- delete 시 자기 자신을 가리켜 무한 루프가 발생하는 오류 수정
=> [hotfix]: be - 객체 Object 제거 오류 수정 

frontend/src/utils/object-from-server.ts, frontend/src/utils/object-to-server.ts
- #280 
- 압축한 text를 UTF8로 인코딩 해줌
=> [hotfix] draw object rendering error

backend/src/object-database/mongoose-object-handler.service.ts, backend/src/socket/db-access.service.ts, backend/src/socket/socket.gateway.ts
- #286 
- Init 과정에서 creator를 닉네임을 치환할 때, Mongoose에서 받아오는 타입이 지정한 Type과 달라서 발생한 문제를 해결함.
=> [hotfix] init 시 creator 수정 시에 지정한 Type과 실제 Type의 불일치로 인한 오류 수정 #286

backend/src/object-database/mongoose-object-handler.service.ts
- #286 
- 로직 수정으로 인해 발생한 오류를 수정함.
=> [hotfix] create 로직 오류 수정 #286

backend/src/socket/socket.gateway.ts
- #292
- Socket.IO 서버 HTTP long polling 비활성화
=> [fix] 소켓 서버 Polling 비활성화 

frontend/src/App.tsx, frontend/src/components/logo/index.tsx, frontend/src/components/user-profile/index.style.tsx, frontend/src/pages/main/workspace-card/index.style.tsx, frontend/src/pages/main/workspace-card/index.tsx, frontend/src/pages/workspace/header/index.tsx, frontend/src/pages/workspace/right-side/index.style.tsx, frontend/src/pages/workspace/toolkit/index.tsx, frontend/src/pages/workspace/zoom-controller/index.style.tsx, frontend/src/pages/workspace/zoom-controller/index.tsx, frontend/src/utils/convert-time.utils.ts
- #289 
- 이미지 width, height, alt 속성 추가
- code splitting을 활용해 번들 사이즈 축소
=> [chore] Lighthouse 성능 측정 및 개선 closes #289

frontend/package-lock.json, frontend/package.json, frontend/src/pages/workspace/whiteboard-canvas/index.tsx, frontend/src/pages/workspace/whiteboard-canvas/types/offscreencanvas.types.ts, frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts, frontend/src/pages/workspace/whiteboard-canvas/useOffscreencanvas.ts, frontend/src/utils/fabric.utils.ts, frontend/src/worker/offcanvas.worker.ts
- closes #282 
- main thread가 사용자와 인터렉션하는 부분만 담당하도록하고 background는 워커쓰레드에서 담당하도록 해서 렌더링 최적화
=> feat - offscreencanvas + web worker로 background로직 처리

frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts, frontend/src/utils/fabric.utils.ts
- #271 
- select UI 개선
- 전
- 후
=> [feat] select 관련 UI 개선 #271

frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts, frontend/src/utils/fabric.utils.ts
=> [fix] object caching 기능 끔 #271

frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
- 어제 발견한 줌 컨트롤러 작동 시 배경 변화 없는 현상 수정했습니다
=> [hotfix] - 줌 컨트롤러 배경 변화 없는 버그 수정
