boostcampwm-2022/web22-BooCrum

.github/workflows/deploy.yml
backend/README.md
backend/src/auth/auth.controller.ts
backend/src/auth/filter/unauth-redirect.filter.ts
backend/src/auth/strategy/github.strategy.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts
backend/src/workspace/workspace.controller.ts
backend/src/workspace/workspace.service.ts

- #5 
- #48 
- #50
1. 워크스페이스 생성 중에 잘못된 팀 ID / 유저 ID가 전달되면 트랜잭션 rollback을 2번하는 오류 수정
2. 특정 워크스페이스의 모든 정보 조회 시 팀 정보가 빠져있는 오류 수정
3. 특정 워크스페이스의 참여자 권한 변경 및 메타데이터 변경 시 await 키워드 누락으로 의도치 않은 응답을 뱉는 오류를 수정함.
4. 워크스페이스의 사용자 참여 여부 판정 시, Where 누락으로 잘못된 판정이 나오는 오류를 수정함.
5. 특정 유저 정보 조회 시, 존재하지 않는 사용자의 ID를 제공한 경우 오류를 반환하도록 로직을 수정함.
1. Github Action 자동 배포 추가 (`main` Branch로 직접 추가 안해도 되는지 테스트.)
2. 로그인 상태 확인 API 추가 (`GET /api/auth/status`)
3. OAuth 로그인 실패 시 리다이렉션을 수행할 수 있도록 수정 (`REDIRECT_FAIL_LOGIN` 환경변수 설정으로 조정 가능)
---
~뭔가 작업 사항이 늘어나는 것은 기분탓입니다~

[fix] API 명세 작성 및 검토, Github Action 추가 closes #5, #48, #50

---

backend/src/object-database/dto/create-object.dto.ts
backend/src/object-database/dto/select-object.dto.ts
backend/src/object-database/object-database.controller.ts
backend/src/object-database/object-database.module.ts
backend/src/object-database/object-handler.service.spec.ts
backend/src/object-database/object-handler.service.ts

- 객체 추가 API 구현
- 객체 삭제 API 구현
- 객체 수정 API 구현
- 객체 조회(전체, 1개) API 구현
- 현재 QueryRunner의 query() 메서드를 통해 SQL문을 직접 입력하여 로직을 구현하였으나, 이 방법이 아닌 방법을 찾아 리팩토링 하면 좋을 것 같음

[feat] Workspace 내부 Object CRUD API 구현 closes #9

---

backend/src/object-database/constant/object-database.constant.ts
backend/src/object-database/object-database.controller.ts
backend/src/object-database/object-database.module.ts
backend/src/object-database/object-database.service.ts
backend/src/object-database/object-handler.service.ts
backend/src/workspace/workspace.module.ts
backend/src/workspace/workspace.service.ts

- #65 
- #8 
- Workspace 생성 시 Object Table도 생성되도록 변경
- Workspace 삭제 시 Object Table도 삭제되도록 변경
- 템플릿 생성에 대비하여 ObjectDatabaseService에 Object Table 복제 기능을 추가
- Workspace Module에서 ObjectDatabase Module을 참조하므로, 반대 방향으로 참조를 시도할 경우 순환참조가 발생하여 Nest에서 컴파일을 거부하니, 이 점 유의할 것. (즉, ObjectDatabase Module이 Workspace Module을 import 할 수 없다.)
- 순환 참조 문제로 인하여 간단한 Workspace 영역 메소드들은 직접 구현하게 됨.
- ObjectHandlerService에서 import하였으나 실질적으로 사용하지 않던 여러 Workspace 관련 요소들을 전부 걷어내었음.

[feat] Workspace 기능과 ObjectDataBase 기능 연결

---

frontend/patches/@types+fabric+4.5.12.patch
frontend/src/pages/main/workspace-list/index.tsx
frontend/src/pages/workspace/whiteboard-canvas/index.tsx
frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
frontend/src/utils/fabric.utils.ts
frontend/src/utils/object.utils.ts

- #105 
- 포스트잇 및 섹션 생성 구현
- canvas에서 moveMode만 확인할 것이 아니라 모든 커서 상태를 확인하고 object를 추가(`addSection`, `addPostIt`)해야할 것 같아서 moveMode에서 mode로 속성을 수정했습니다.
- object가 이동할 때 object edit menu의 위치가 아직 안정적이지 않아 계속해서 수정해볼 예정입니다.

[feat] object 생성 구현 closes #105

---

frontend/src/components/user-profile/index.tsx
frontend/src/context/auth.ts
frontend/src/context/user.ts
frontend/src/hooks/useAuth.ts

- userProfile을 전역 상태로 리팩토링
- userProfile이 header에서도 쓰이고, 소켓에서도 자기가 보낸 이벤트를 필터링할 때 쓰일거라(그리고 더 쓰이지 않을까요?) selector로 비동기 전역 상태로 만들었습니다. 
- 부모 자식 관계가 아닌 2곳 이상에 쓰일 떄 전역 상태로 분리하고 있습니다

[refactor] - userProfile을 전역 상태로 관리

---

frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts

- #123 
- EditMenu 위치 값 재설정
- Zoom 했을 때 메뉴 위치 변경
- Resize 했을 때 메뉴 위치 변경
- Object를 이동 시켰을 때 위치 변경
- getCoords() 는 모니터 화면기준에서 오브젝트의 좌표를 4개의점으로 알려줍니다.
- left, top 속성은 canvas 안의 좌표계를 기준의 위치를 나타냅니다.

[feat] EditMenu 위치 설정 closes #123

---

backend/src/migrations/1669621214094-change-object-columns.ts
backend/src/object-database/object-handler.service.ts
backend/src/socket/socket.gateway.ts
backend/src/user/user.service.ts
backend/src/util/socket/user.dao.ts

- #132
- #107
- 소켓의 User 정보 중 isGuest 값이 실제와 반대로 기록되는 오류 수정
- 최초 연결 시 전달하는 유저 정보에서 Role이 누락되었던 문제 해결
- 최초 연결 시 전달할 데이터에서 제거되어야 했던 데이터들이 제거되지 않았던 문제 해결
- 갱신/삭제 로직에서 의도된 오류들 중 캐치되지 않아 500 오류를 반환하던 문제를 해결함
- 마이그레이션 코드 중 MySQL 버전 문제로 RENAME COLUMN 대신 CHANGE 구문으로 컬럼명 변경
- ObjectHandler에서 Object 정보 수정 시 제거되지 않은 정보(워크스페이스 ID)로 인하여 update가 실패하던 오류 수정

[hotfix] 화이트보드 객체 업데이트 및 삭제 로직 오류 긴급 수정 #132

---

backend/src/socket/socket.gateway.ts

- Socket의 `update_object`와 `create_object` 이벤트를 통해 섹션을 다룰 때 섹션 제목의 글자 수가 50자 이상일 경우 예외 처리

[fix] Section 제목 최대 길이 설정 closes #138

---

frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
frontend/src/types/fabric-options.d.ts
frontend/src/utils/fabric.utils.ts
frontend/src/utils/object-from-server.ts
frontend/src/utils/object.utils.ts

- #126 
- 함수형(?)으로 Section Object 구현
- section 타이틀 배경은 동적으로 렌더링
- object index leveling 추가
- object 추가 될 때 마다 postit이 맨 위로 오게 설정
- 섹션이 움직이면 안에 있는 PostIt 같이 움직이면 좋겠죠...? ㅎㅎ...

[feat] addSection 구현 closes #126

---

backend/src/socket/socket.gateway.ts

- #154
- typo로 인해 값을 전달받은 값을 못찾아오는 오류 수정

[hotfix] (un)select에서 typo로 인해 값을 못찾는 오류 수정 closes #154

---

frontend/src/context/user.ts
frontend/src/data/workspace-role.ts
frontend/src/pages/main/workspace-menu/index.tsx
frontend/src/pages/workspace/layout/index.tsx
frontend/src/pages/workspace/whiteboard-canvas/index.tsx
frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
frontend/src/utils/fabric.utils.ts

- #128 
- Guest 권한(`role: 0`)인 경우 Toolkit을 사용할 수 없고 커서모드를 무조건 move로 사용 가능하도록 설정
- move mode 시 캔버스에 올라간 모든 object를 `selectable: false`로 해두어 object를 선택할 수 없게 설정
- `init`시 초기화한 정보를 전역 상태에 저장해 다른 컴포넌트에서 사용할 수 있게 하고, ref에 저장해 해당 hook 내에서 사용할 수 있게 설정
- `myInfoInWorkspace`를 전역 state로 관리하는 경우 setRecoilState 후에 effect 안에서 값이 업데이트되지 않기 때문에 useSocket 안에서만 사용할 수 있는 ref를 추가적으로 선언해주거나 아니면 state가 바뀔 때마다 이벤트를 off 후 새로 on해야 할 것 같은데 ref를 선언하는게 그나마 효율적이라 생각해서 그런 방식으로 구현했습니다. 더 좋은 방법이 있으시다면 말씀해주세요!

[feat] 권한에 따른 인터페이스 처리 closes #128

---

frontend/patches/@types+fabric+4.5.12.patch
frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
frontend/src/types/fabric-options.d.ts
frontend/src/utils/object-from-server.ts
frontend/src/utils/object.utils.ts

- #127 
- ObjectType에 editable 타입 추가
- 더블 클릭 시 editableText를 추가로 렌더링
- editable에서 changed 이벤트 이용해서 실제 Object(PostIt, Section)의 Text를 변경
- 실제 Object의 Text는 visible로 숨기기만 함
- editable Text와 실제 Text의 위치 동기화
- editable Text랑 실제 Text랑 사이즈 싱크가 안맞아서 정돈을 해야겠다. (PostIt만 해당)

[feat] Text 편집 기능 구조 변경 closes #127

---

frontend/package-lock.json
frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
frontend/src/utils/fabric.utils.ts
frontend/src/utils/object.utils.ts

- #176 
- move mode에서 편집 모드로 진입할 수 없게 수정
- hover 시 커서 수정
- move mode에서 포스트잇을 더블클릭하면 편집모드로 들어가지는데, 이렇게 설정될 경우 게스트인 경우에도 편집할 수 있는 문제가 발생하기 때문에 move mode에서는 편집모드로 들어갈 수 없도록 수정해두었습니다.
- edit 후 다시 원래 커서로 돌아올때 두 가지 방법이 있을 것 같습니다. 커서를 무조건 select로 변경하거나 이전에 사용했던 모드로 돌아가는 방법이 인데요, 커서를 select로 변환하기 위해서는 전역으로 관리하던 state에 접근해서 setState로 수정해야하는데 일반 함수에서는 접근할 수 없으니까 그냥 이전에 사용했던 모드를 기억했다가 돌아가도록 설정해두었습니다.

[hotfix] move 모드에서 포스트잇 편집되는 부분 수정 closes #176

---

frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
frontend/src/types/fabric-options.d.ts
frontend/src/utils/fabric.utils.ts
frontend/src/utils/object-from-server.ts
frontend/src/utils/object.utils.ts

- #127
- #126 
- 오브젝트 위에 오브젝트 추가 가능
- 오브젝트 추가 하고나면 Select 모드로 변경
- PostIt 작성자 표시
- 서버에서 받아온 Object가 사라지는 버그 수정
- 서버에서 받아온 Obejct width, height 설정 주석처리
- postit.set({scaleX, scaleY})로 설정해주면 자동으로 PostIt 사이즈 동기화 될 겁니다. (아니면 유감...)

[feat] 작성자 표시 및 addObject 개선 closes #126

---

backend/src/socket/dto/object-scale.dto.ts
backend/src/socket/socket.gateway.ts

- #161 
- ObjectScaleDTO에서 dleft와 dtop을 제거하고, left와 top을 추가함.
- 이벤트 emit 시 left와 top을 client에서 제공하는 값을 제공하도록 변경
- 이벤트 emit 시 dleft, dtop을 제공하지 않음

[fix] scale-object 이벤트 요청 응답 데이터 구조 변경 #161

---

backend/src/socket/db-access.service.ts
backend/src/socket/dto/change-role.dto.ts
backend/src/socket/socket.gateway.ts

- #216 
- Role 권한 상승 Event Handler 추가. (`Owner` 권한만 가능. 부여 가능한 권한은 `Viewer`와 `Editor`임.)
- Db 접근용 Service에 DB 권한 수정 메서드 추가

[feat]  Role 권한 수정 Event Handler 추가 closes #216

---

frontend/src/pages/workspace/whiteboard-canvas/index.style.tsx
frontend/src/pages/workspace/whiteboard-canvas/index.tsx
frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
frontend/src/utils/fabric.utils.ts

- #228 
- init이 완료된 뒤 canvas가 뜨도록 설정
- Pattern을 background로 얹는 작업이 시간이 많이 걸리는지 fabric 내에서 해결하려고 했는데 해결이 안돼서 init이 완료되고 모든 오브젝트가 있는 화면을 사용자가 볼 수 있도록 상태를 하나 더 추가해주었습니다.

[chore] background 깜빡임 현상 수정 closes #228

---

frontend/src/pages/workspace/whiteboard-canvas/index.tsx
frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
frontend/src/pages/workspace/whiteboard-canvas/useCursorWorker.ts
frontend/src/worker/cursor.worker.ts
frontend/src/worker/object.worker.ts

- closes #244 
- 30fps에 맞춰서 33ms마다 마우스커서 이동 이벤트를 배치처리해서 전송했습니다.
- 연산을 webworker에서 처리했습니다
- 기존 3~ 4번 -> 1번으로 이벤트수가 절감했습니다

[feat] mouse cursor batching + webworker 최적화

---

backend/src/socket/pipe/object-updating.pipe.ts
backend/src/socket/socket.gateway.ts

BE - Object Update 관련 범용 이벤트 추가
- `updating_object` 이벤트 구현
UpdateObjectDTO는 그대로 두고 pipe를 하나 더 만들었습니다.
기존 사용하던 UpdateObjectDTO도 type은 optional인데 transform-pipe에서 type을 통해 검증을 하기 때문에 필수적이였던 것인데, 지금은 기존 dto는 써도 될 것 같아서 pipe를 별도로 추가하였습니다.

[feat] updating_object 이벤트 구현 closes #262

---

frontend/src/utils/object-from-server.ts
frontend/src/utils/object.utils.ts

- #273 
- 포스트잇 텍스트 공동 편집
- 포스트잇의 타입은 TextBox로 내부의 textarea까지 수정해야 공동 편집 상태가 정상적으로 작동하더라구요.
- 근데 섹션의 타이틀은 IText로 Textbox처럼 내부에 textarea를 사용하던데 막상 IText의 textarea를 수정하려 하니까 값이 없다고 떠서 수정이 안되네요,,?

[feat] 텍스트 공동 편집 closes #273

---

frontend/src/utils/fabric.utils.ts

- #271
- 조금 이상하지만 강제로 draw object를 맨 위로 올렸음
- draw는 항상 맨 위에 위치시킴

[fix] draw object index leveling closes #271
